"""Compile the editable layout and asset inventory into a flat player script."""
import configparser
import hashlib
import json
import math
import numpy as np
from PIL import Image


def rectangles(root):
    specs = json.loads((root / 'source/scripts/layout-descriptors.json').read_text())
    ini = configparser.ConfigParser()
    ini.read(root / 'source/hud/hud_layout.ini')
    result = {}
    for name, (w, h) in specs['roots'].items():
        section = ini[name]
        size = section.getint('size')
        result[name] = [section.getint('x'), section.getint('y'),
                        math.trunc(w * size / max(w, h)), math.trunc(h * size / max(w, h))]
    pending = dict(specs['children'])
    while pending:
        before = len(pending)
        for name, spec in list(pending.items()):
            parent = 'comms.child_content' if spec['nested_comms'] else spec['parent']
            if parent not in result:
                continue
            p = result[parent]
            axis = 3 if spec['parent'] == 'missile_display' else 2
            denominator = specs['roots'][spec['parent']][axis - 2]
            section = ini[name] if name in ini else {}
            x = float(section.get('offset_x', spec['offset'][0]))
            y = float(section.get('offset_y', spec['offset'][1]))
            percent = int(section.get('scale_percent', 100))
            result[name] = [p[0] + math.trunc(x * p[axis] / denominator),
                            p[1] + math.trunc(y * p[axis] / denominator),
                            *[max(1, math.trunc(math.trunc(n * p[axis] / denominator) * percent / 100))
                              for n in spec['size']]]
            del pending[name]
        assert len(pending) < before, 'Unresolved layout parent'
    return result


def build(root, output):
    plan = json.loads((root / 'tools/hud-export-plan.json').read_text())
    assets = {item['key']: item['outputs'][0] for item in plan if item['outputs']}
    lines = ['-- Generated by tools/build_script.py. Edit source/scripts/hud.luau and source/hud/hud_layout.ini.',
             'local rects = {']
    for name, rect in rectangles(root).items():
        lines.append(f'    [{json.dumps(name)}] = {{{", ".join(map(str, rect))}}},')
    lines += ['}', 'local assets = {']
    for name, file in sorted(assets.items()):
        lines.append(f'    [{json.dumps(name)}] = {json.dumps(file)},')
    lines += ['}', 'local commsInkBearing = {']
    metrics = json.loads((root / 'source/scripts/comms-ink-metrics.json').read_text())
    assert hashlib.sha256((root / 'source/runtime-meta/rc_comms.ttf').read_bytes()).hexdigest() == metrics['outline_font_sha256'], 'Regenerate comms ink metrics after changing the font'
    for code, bearing in metrics['ink_bearings'].items():
        lines.append(f'    [{code}] = {bearing},')
    lines += ['}', 'local gunArtTop = {']
    for item in plan:
        if item['key'].startswith('gunnery/ship_wireframes/') and item['key'].endswith('/wireframe'):
            with Image.open(root / item['source']) as picture:
                top = picture.convert('RGBA').getchannel('A').getbbox()[1] / picture.height
            lines.append(f'    [{json.dumps(item["key"])}] = {top!r},')
    lines += ['}', 'local assetPixels = {']
    for item in plan:
        if item['outputs']:
            with Image.open(root / item['source']) as picture:
                w, h = picture.size
            if 'crop' in item:
                x0, y0, x1, y1 = item['crop']; w, h = x1-x0, y1-y0
            if item['recipe'] == 'missile-1024': w, h = 1024, 1024
            lines.append(f'    [{json.dumps(item["key"])}] = {w*h},')
    lines += ['}', 'local artBounds = {']
    for item in plan:
        if item['key'].startswith(('schems/player_dam/', 'schems/ally_target/', 'schems/enemy_target/')) and '/damage_layers/' not in item['key']:
            a = np.array(Image.open(root / item['source']).convert('RGBA'))
            halo = (a[:,:,3] > 0) & (a[:,:,3] < 240) & np.all(a[:,:,:3] <= 4, axis=2)
            visible = a[:,:,3] > 8
            if halo.sum() >= 256: visible &= ~halo
            yy, xx = np.where(visible)
            box = [float(xx.min()/a.shape[1]), float(yy.min()/a.shape[0]), float((xx.max()+1)/a.shape[1]), float((yy.max()+1)/a.shape[0])]
            lines.append(f'    [{json.dumps(item["key"])}] = {{{", ".join(map(str,box))}}},')
    lines += ['}']
    mapping = json.loads((root / 'source/scripts/ship-art.json').read_text())
    for table, key in [('smallShipArt', 'small'), ('largeShipArt', 'large')]:
        lines.append('local '+table+' = {')
        lines.extend(f'    [{json.dumps(k)}] = {json.dumps(v)},' for k,v in mapping[key].items())
        lines.append('}')
    radar = sorted(k for k in assets if k.startswith('radar/'))
    lines.append('local radarArt = {'+', '.join(json.dumps(k) for k in radar)+'}')
    template = (root / 'source/scripts/hud.luau').read_text()
    template = template.replace('-- ADDITIONAL_INSTRUMENTS', (root / 'source/scripts/instruments.luau').read_text())
    lines.append(template)
    (output / 'recommissioned.luau').write_text('\n'.join(lines))
