from pathlib import Path
import bpy,numpy as np,json,hashlib
D=Path('authoring://Shroud/worn');W=D/'work/refinement_v2';M=D/'maps/refinement_v2';prior=json.loads((W/'prior_project_state.json').read_text());bpy.ops.wm.open_mainfile(filepath=prior['latest_scene']);s=bpy.context.scene;obs=[o for o in s.objects if o.type=='MESH'];bpy.context.view_layer.update()
def signature():return hashlib.sha256(json.dumps({o.name:([list(v.co) for v in o.data.vertices],[list(p.vertices) for p in o.data.polygons],[list(q.vector) for q in o.data.corner_normals],{u.name:[list(q.uv) for q in u.data] for u in o.data.uv_layers},[list(r) for r in o.matrix_world]) for o in obs},sort_keys=True).encode()).hexdigest()
sig=signature();N=4096;S=1254/N;yy,xx=np.mgrid[:N,:N].astype(np.float32);X=(xx+.5)*S;Y=(yy+.5)*S;del xx,yy
records={k:dict(v) for k,v in prior['maps'].items()}
def load(path,channels=1):
 im=bpy.data.images.load(str(path),check_existing=False);im.colorspace_settings.name='Non-Color'
 if tuple(im.size)!=(N,N):im.scale(N,N)
 a=np.empty(N*N*4,np.float32);im.pixels.foreach_get(a);a=a.reshape(N,N,4)[::-1,:,:channels].copy();bpy.data.images.remove(im);return a if channels>1 else a[:,:,0]
def old(kind,channels=1):return load(prior['maps'][kind]['path'],channels)
def save(a,kind,colour=False):
 data=np.ones((N,N,4),np.float32);data[:,:,:3]=a if a.ndim==3 else a[:,:,None];im=bpy.data.images.new('Shroud v2 '+kind,N,N,alpha=False,float_buffer=True);im.colorspace_settings.name='Non-Color';im.pixels.foreach_set(np.ascontiguousarray(data[::-1]).ravel());im.filepath_raw=str(M/f'shroud_worn_{kind}_4k_v2.png');im.file_format='PNG';s.render.image_settings.color_depth='8' if colour else '16';im.save();path=im.filepath_raw;bpy.data.images.remove(im);im=bpy.data.images.load(path,check_existing=False);im.colorspace_settings.name='sRGB' if colour else 'Non-Color';im.pack();records[kind]={'path':path,'sha256':hashlib.sha256(Path(path).read_bytes()).hexdigest()};return im

def smooth(a,b,x):
 t=np.clip((x-a)/(b-a),0,1);return t*t*(3-2*t)
def polygon(points):
 p=np.array(points);d=np.full(X.shape,1e6,np.float32);area=np.sum(p[:,0]*np.roll(p[:,1],-1)-p[:,1]*np.roll(p[:,0],-1))
 for a,b in zip(p,np.roll(p,-1,axis=0)):
  v=b-a;d=np.minimum(d,np.sign(area)*(v[0]*(Y-a[1])-v[1]*(X-a[0]))/np.linalg.norm(v))
 return d
regions=json.loads((D/'work/reconstruction_v1/regions.json').read_text());radiator=np.zeros((N,N),np.float32)
for bank in regions['radiators']:radiator=np.maximum(radiator,smooth(0,2,polygon(bank['polygon'])))
# Strengthen only wing-edge banks: no new texture-noise relief or changes elsewhere.
glass=old('glass');graphics=old('flat_graphics');radiator*=1-np.maximum(glass,graphics);save(radiator,'radiator_refinement_mask')
h0=old('height')*8-5;h=h0*(1+1.4*radiator);dy,dx=np.gradient(h,S);derived=np.stack((-dx,dy,np.ones_like(h)),-1);derived/=np.linalg.norm(derived,axis=-1,keepdims=True)
normal0=old('normal',3)*2-1;support=radiator>0
for axis in (0,1):support|=np.roll(radiator,1,axis)>0;support|=np.roll(radiator,-1,axis)>0
normal=normal0.copy();normal[support]=derived[support];normal_im=save(normal*.5+.5,'normal');save((h+8)/12,'height')
angle0=np.degrees(np.arccos(np.clip(normal0[:,:,2],-1,1)));angle=np.degrees(np.arccos(np.clip(normal[:,:,2],-1,1)));flanks=(radiator>.999)&(angle0>8)&(angle0<70);stats={'radiator_height_multiplier':2.4,'radiator_flank_angle_median_before':float(np.median(angle0[flanks])),'radiator_flank_angle_median_after':float(np.median(angle[flanks]))};del derived,dx,dy,h0,h,normal0,normal,angle0,angle
# Integrate the image-generation glass edit only into the existing pane mask.
base0=old('basecolor',3);generated=load(M/'shroud_glass_edit_generated_v2.png',3);base=base0*(1-glass[:,:,None])+generated*glass[:,:,None];base_im=save(base,'basecolor',True)
# A broad, smoother response brings back highlights generated by scene lights.
fin=old('fin_mask');rough0=old('roughness');rough=rough0*(1-radiator)+(.72-.38*fin)*radiator;rough=rough*(1-glass)+(.135+.018*(.5+.5*np.sin(X*.19)*np.sin(Y*.11)))*glass
metal0=old('metallic');metal=metal0*(1-radiator)+(.12+.76*fin)*radiator;metal*=1-glass
spec0=old('specular');spec=spec0*(1-glass)+.5*glass;coat0=old('coat');coat=coat0*(1-glass)+.24*glass
maps={'basecolor':base_im,'normal':normal_im,'roughness':save(rough,'roughness'),'metallic':save(metal,'metallic'),'specular':save(spec,'specular'),'coat':save(coat,'coat')}
stats.update(glass_roughness_median_before=float(np.median(rough0[glass>.99])),glass_roughness_median_after=float(np.median(rough[glass>.99])),glass_metallic_max=float(metal[glass>.9999].max()))
oldmat=obs[0].data.materials[0];mat=oldmat.copy();mat.name='Shroud_Worn_PBR_v2'
for kind,im in maps.items():mat.node_tree.nodes['Delivered '+kind].image=im
for o in obs:
 for i,m in enumerate(o.data.materials):
  if m==oldmat:o.data.materials[i]=mat
assert signature()==sig
s['pbr_status']='Shroud v2: stronger wing-edge radiator relief, removed baked glass stripe, smoother reflective glass; all other domains preserved.';bpy.context.preferences.filepaths.save_version=0;bpy.ops.wm.save_as_mainfile(filepath=str(D/'shroud_worn_pbr_v2.blend'))
validation={'source_scene':prior['latest_scene'],'scene':str(D/'shroud_worn_pbr_v2.blend'),'geometry_signature':sig,'geometry_uv_native_normals_preserved':True,'maps':records,'material_statistics':stats,'height_decode':'height PNG * 12 - 8 (1254 atlas pixel units); baked into tangent normal, no displacement','parts':len(obs),'stored_LOD0_triangles':sum(len(o.data.polygons) for o in obs),'intact_visible_LOD0_triangles':sum(p.material_index==0 for o in obs for p in o.data.polygons),'engine_validation':'not_tested','glass_edit_method':'Built-in image generation, composited only through original glass mask; frame and all other basecolour pixels protected.'}
(W/'validation.json').write_text(json.dumps(validation,indent=2));print('REFINEMENT_COMPLETE',stats,flush=True)
